api/urls.py
from django.urls import path,include
from .views import *
from .user_views import *

urlpatterns = [
     path('api/', SorovApiView.as_view()),
     # home
     path('hokim/',hokimpaneli,name='home'),
     path("hokim/1124424434354235412425/", hbarchasi, name="hammasi"),
     path('',hokimiyatPanel,name='hp'),
     # hps
     path('ars1/',filter_ariza_tur1,name='at1'),
     path('ars2/',filter_ariza_tur2,name='at2'),
     path('ars3/',filter_ariza_tur3,name='at3'),
     path('ars4/',filter_ariza_tur4,name='at4'),
     path('ars5/',filter_ariza_tur5,name='at5'),
     path('ars6/',filter_ariza_tur6,name='at6'),
     path('ars7/',filter_ariza_tur7,name='at7'),
     path('ars8/',filter_ariza_tur8,name='at8'),
     path('ars9/',filter_ariza_tur9,name='at9'),
     path('ars10/',filter_ariza_tur10,name='at10'),
     path('ars11/',filter_ariza_tur11,name='at11'),
     path('ars12/',filter_ariza_tur12,name='at12'),
     path('ars13/',filter_ariza_tur13,name='at13'),
     path('ars14/',filter_ariza_tur14,name='at14'),
     path('ars15/',filter_ariza_tur15,name='at15'),
     path('ars16/',filter_ariza_tur16,name='at16'),
     path('ars17/',filter_ariza_tur17,name='at17'),
     path('ars18/',filter_ariza_tur18,name='at18'),
     path('ars19/',filter_ariza_tur19,name='at19'),
     path('ars20/',filter_ariza_tur20,name='at20'),
     path('ars21/',filter_ariza_tur21,name='at21'),
     path('ars22/',filter_ariza_tur22,name='at22'),
     path('ars23/',filter_ariza_tur23,name='at23'),
     path('ars24/',filter_ariza_tur24,name='at24'),
     path('ars25/',filter_ariza_tur25,name='at25'),
     path('ars26/',filter_ariza_tur26,name='at26'),
     path('ars27/',filter_ariza_tur27,name='at27'),

     path('barchasi/',barcha,name='barchasi'),
     path('bajarilgan/',bajarilgan,name='bajarilgan'),
     path('md/',muddat,name='md'),
     path('bj/',bj,name='bj'),
     path('del/<int:id>',delete,name='del'),
     path('bja/<int:pk>',Change.as_view(),name='bja'),
     # user views-
     path('',include('django.contrib.auth.urls')),
     path('saiduwa/',CreateBlog.as_view(),name='new'),
     path('rahmat/',ramat,name='rahmat'),
     path('fwa/',fuwr,name='usw')
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('',include('api.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
# Create your models here.
class Sorov(models.Model):
    fish = models.CharField(max_length=500,verbose_name='To`liq ismingizni kiriting?')
    idpassport = models.CharField(max_length=500,verbose_name='pasport seriasini kiriting')
    Yashashmanzili = models.CharField(max_length=500)
    
    mfynomi = models.CharField(max_length=500)
    kochanomi = models.CharField(max_length=500)
    telefonraqami = models.CharField(max_length=500)
    rasmvavidio = models.CharField(max_length=500)
    ariza_mazmuni = models.CharField(max_length=500)
    matn = models.TextField()

    def __str__(self) -> str:
        return self.fish
    
    def get_absolute_url(self):
        return reverse('rahmat')
class Orinbosar(models.Model):
    name = models.CharField(max_length=500)   
    def __str__(self) -> str:
        return self.name
class Tashkilotlar(models.Model):
    name = models.CharField(max_length=500)   
    def __str__(self) -> str:
        return self.name    

class Hokimiyat(models.Model):
    tel_name = models.CharField(max_length=500)
    orinbosar = models.ForeignKey(Orinbosar,on_delete=models.CASCADE,null=True)
    tashkilot = models.ForeignKey(Tashkilotlar,on_delete=models.CASCADE,null=True)
    muddat = models.DateField(auto_now_add=True)
    bajarildi = models.BooleanField(default=False,null=True)
    muddat_holati = models.BooleanField(default=False,null=True)

    def __str__(self) -> str:
        return self.murajat

templates/hp_az/hp_az1.html
{% extends "base_hp.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <style>
    #div_id_murajat{
      overflow: hidden;
      display:flex ;
      flex-direction: column;
    }
    #div_id_tashkilot{
      display:flex ;
      flex-direction: column;
    }
    #id_tashkilot{
      height: 33px;
    }
    #id_murajat{
      height: 33px;
    }
    #div_id_bajarildi{
      display: none;
    }
    #div_id_muddat_holati{
      display: none;
    }
    #div_id_orinbosar{
      display:flex ;
      flex-direction: column;
    }
    #id_orinbosar{
      height: 33px;
    }
    #id_orinbosar option:nth-child(1){
      display: none;
    }
    #id_murajat option:nth-child(1){
      display: none;
    }
  </style>
              <form method="post" style="display: flex; justify-content: space-evenly; align-items: center;">
                {% csrf_token %}
                {{ form | crispy }}
                <div>
                  <button class="btn btn-default btn-flat" style="margin-top: 23px;"
                  type="submit">yuborish
                </button>
                </div>
                
              </form>
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Ism Familiya Sharif</th>
                    <th scope="col">Id Passpord</th>
                    <th scope="col">Yash Manzili</th>
                    <th scope="col">MFY Nomi</th>
                    <th scope="col">Ko`cha Nomi</th>
                    <th scope="col">Tel Raqam</th>
                    <th scope="col">Rasm yoki Vidio</th>
                    <th scope="col">Ariza Tur</th>
                    <th scope="col">matn</th>
                  </tr>
                </thead>
                <tbody>
                {% for ariza in ariza %}
                  
                  <tr>
                    <th scope="row">{{ ariza.id }}</th>
                    <td>{{ ariza.fish }}</td>
                    <td>{{ ariza.idpassport }}</td>
                    <td>{{ ariza.Yashashmanzili }}</td>
                    <td>{{ ariza.mfynomi }}</td>
                    <td>{{ ariza.kochanomi }}</td>
                    <td>{{ ariza.telefonraqami }}</td>
                    <td>{{ ariza.rasmvavidio }}</td>
                    <td>{{ ariza.ariza_mazmuni }}</td>
                    <td><a href='{% url "del" ariza.id %}'>del</a></td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>       
{% endblock content %}

templates/hp_az/hp_az10.html
{% extends "base_hp.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <style>
    #div_id_murajat{
      overflow: hidden;
      display:flex ;
      flex-direction: column;
    }
    #div_id_tashkilot{
      display:flex ;
      flex-direction: column;
    }
    #id_tashkilot{
      height: 33px;
    }
    #id_murajat{
      height: 33px;
    }
    #div_id_bajarildi{
      display: none;
    }
    #div_id_muddat_holati{
      display: none;
    }
    #div_id_orinbosar{
      display:flex ;
      flex-direction: column;
    }
    #id_orinbosar{
      height: 33px;
    }
    #id_orinbosar option:nth-child(1){
      display: none;
    }
    #id_murajat option:nth-child(1){
      display: none;
    }
  </style>
              <form method="post" style="display: flex; justify-content: space-evenly; align-items: center;">
                {% csrf_token %}
                {{ form | crispy }}
                <div>
                  <button class="btn btn-default btn-flat" style="margin-top: 23px;"
                  type="submit">yuborish
                </button>
                </div>
                
              </form>
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Ism Familiya Sharif</th>
                    <th scope="col">Id Passpord</th>
                    <th scope="col">Yash Manzili</th>
                    <th scope="col">MFY Nomi</th>
                    <th scope="col">Ko`cha Nomi</th>
                    <th scope="col">Tel Raqam</th>
                    <th scope="col">Rasm yoki Vidio</th>
                    <th scope="col">Ariza Tur</th>
                    <th scope="col">matn</th>
                  </tr>
                </thead>
                <tbody>
                {% for ariza in ariza %}
                  
                  <tr>
                    <th scope="row">{{ ariza.id }}</th>
                    <td>{{ ariza.fish }}</td>
                    <td>{{ ariza.idpassport }}</td>
                    <td>{{ ariza.Yashashmanzili }}</td>
                    <td>{{ ariza.mfynomi }}</td>
                    <td>{{ ariza.kochanomi }}</td>
                    <td>{{ ariza.telefonraqami }}</td>
                    <td>{{ ariza.rasmvavidio }}</td>
                    <td>{{ ariza.ariza_mazmuni }}</td>
                    <td><a href='{% url "del" ariza.id %}'>del</a></td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>       
{% endblock content %}

templates/hp_az/hp_az13.html
{% extends "base_hp.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <style>
    #div_id_murajat{
      overflow: hidden;
      display:flex ;
      flex-direction: column;
    }
    #div_id_tashkilot{
      display:flex ;
      flex-direction: column;
    }
    #id_tashkilot{
      height: 33px;
    }
    #id_murajat{
      height: 33px;
    }
    #div_id_bajarildi{
      display: none;
    }
    #div_id_muddat_holati{
      display: none;
    }
    #div_id_orinbosar{
      display:flex ;
      flex-direction: column;
    }
    #id_orinbosar{
      height: 33px;
    }
    #id_orinbosar option:nth-child(1){
      display: none;
    }
    #id_murajat option:nth-child(1){
      display: none;
    }
  </style>
              <form method="post" style="display: flex; justify-content: space-evenly; align-items: center;">
                {% csrf_token %}
                {{ form | crispy }}
                <div>
                  <button class="btn btn-default btn-flat" style="margin-top: 23px;"
                  type="submit">yuborish
                </button>
                </div>
                
              </form>
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Ism Familiya Sharif</th>
                    <th scope="col">Id Passpord</th>
                    <th scope="col">Yash Manzili</th>
                    <th scope="col">MFY Nomi</th>
                    <th scope="col">Ko`cha Nomi</th>
                    <th scope="col">Tel Raqam</th>
                    <th scope="col">Rasm yoki Vidio</th>
                    <th scope="col">Ariza Tur</th>
                    <th scope="col">matn</th>
                  </tr>
                </thead>
                <tbody>
                {% for ariza in ariza %}
                  
                  <tr>
                    <th scope="row">{{ ariza.id }}</th>
                    <td>{{ ariza.fish }}</td>
                    <td>{{ ariza.idpassport }}</td>
                    <td>{{ ariza.Yashashmanzili }}</td>
                    <td>{{ ariza.mfynomi }}</td>
                    <td>{{ ariza.kochanomi }}</td>
                    <td>{{ ariza.telefonraqami }}</td>
                    <td>{{ ariza.rasmvavidio }}</td>
                    <td>{{ ariza.ariza_mazmuni }}</td>
                    <td><a href='{% url "del" ariza.id %}'>del</a></td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>       
{% endblock content %}

templates/hp_az/hp_az15.html
{% extends "base_hp.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <style>
    #div_id_murajat{
      overflow: hidden;
      display:flex ;
      flex-direction: column;
    }
    #div_id_tashkilot{
      display:flex ;
      flex-direction: column;
    }
    #id_tashkilot{
      height: 33px;
    }
    #id_murajat{
      height: 33px;
    }
    #div_id_bajarildi{
      display: none;
    }
    #div_id_muddat_holati{
      display: none;
    }
    #div_id_orinbosar{
      display:flex ;
      flex-direction: column;
    }
    #id_orinbosar{
      height: 33px;
    }
    #id_orinbosar option:nth-child(1){
      display: none;
    }
    #id_murajat option:nth-child(1){
      display: none;
    }
  </style>
              <form method="post" style="display: flex; justify-content: space-evenly; align-items: center;">
                {% csrf_token %}
                {{ form | crispy }}
                <div>
                  <button class="btn btn-default btn-flat" style="margin-top: 23px;"
                  type="submit">yuborish
                </button>
                </div>
                
              </form>
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Ism Familiya Sharif</th>
                    <th scope="col">Id Passpord</th>
                    <th scope="col">Yash Manzili</th>
                    <th scope="col">MFY Nomi</th>
                    <th scope="col">Ko`cha Nomi</th>
                    <th scope="col">Tel Raqam</th>
                    <th scope="col">Rasm yoki Vidio</th>
                    <th scope="col">Ariza Tur</th>
                    <th scope="col">matn</th>
                  </tr>
                </thead>
                <tbody>
                {% for ariza in ariza %}
                  
                  <tr>
                    <th scope="row">{{ ariza.id }}</th>
                    <td>{{ ariza.fish }}</td>
                    <td>{{ ariza.idpassport }}</td>
                    <td>{{ ariza.Yashashmanzili }}</td>
                    <td>{{ ariza.mfynomi }}</td>
                    <td>{{ ariza.kochanomi }}</td>
                    <td>{{ ariza.telefonraqami }}</td>
                    <td>{{ ariza.rasmvavidio }}</td>
                    <td>{{ ariza.ariza_mazmuni }}</td>
                    <td><a href='{% url "del" ariza.id %}'>del</a></td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>       
{% endblock content %}

templates/hp_az/hp_az19.html
{% extends "base_hp.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <style>
    #div_id_murajat{
      overflow: hidden;
      display:flex ;
      flex-direction: column;
    }
    #div_id_tashkilot{
      display:flex ;
      flex-direction: column;
    }
    #id_tashkilot{
      height: 33px;
    }
    #id_murajat{
      height: 33px;
    }
    #div_id_bajarildi{
      display: none;
    }
    #div_id_muddat_holati{
      display: none;
    }
    #div_id_orinbosar{
      display:flex ;
      flex-direction: column;
    }
    #id_orinbosar{
      height: 33px;
    }
    #id_orinbosar option:nth-child(1){
      display: none;
    }
    #id_murajat option:nth-child(1){
      display: none;
    }
  </style>
              <form method="post" style="display: flex; justify-content: space-evenly; align-items: center;">
                {% csrf_token %}
                {{ form | crispy }}
                <div>
                  <button class="btn btn-default btn-flat" style="margin-top: 23px;"
                  type="submit">yuborish
                </button>
                </div>
                
              </form>
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Ism Familiya Sharif</th>
                    <th scope="col">Id Passpord</th>
                    <th scope="col">Yash Manzili</th>
                    <th scope="col">MFY Nomi</th>
                    <th scope="col">Ko`cha Nomi</th>
                    <th scope="col">Tel Raqam</th>
                    <th scope="col">Rasm yoki Vidio</th>
                    <th scope="col">Ariza Tur</th>
                    <th scope="col">matn</th>
                  </tr>
                </thead>
                <tbody>
                {% for ariza in ariza %}
                  
                  <tr>
                    <th scope="row">{{ ariza.id }}</th>
                    <td>{{ ariza.fish }}</td>
                    <td>{{ ariza.idpassport }}</td>
                    <td>{{ ariza.Yashashmanzili }}</td>
                    <td>{{ ariza.mfynomi }}</td>
                    <td>{{ ariza.kochanomi }}</td>
                    <td>{{ ariza.telefonraqami }}</td>
                    <td>{{ ariza.rasmvavidio }}</td>
                    <td>{{ ariza.ariza_mazmuni }}</td>
                    <td><a href='{% url "del" ariza.id %}'>del</a></td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>       
{% endblock content %}

templates/hp_az/hp_az2.html
{% extends "base_hp.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <style>
    #div_id_murajat{
      overflow: hidden;
      display:flex ;
      flex-direction: column;
    }
    #div_id_tashkilot{
      display:flex ;
      flex-direction: column;
    }
    #id_tashkilot{
      height: 33px;
    }
    #id_murajat{
      height: 33px;
    }
    #div_id_bajarildi{
      display: none;
    }
    #div_id_muddat_holati{
      display: none;
    }
    #div_id_orinbosar{
      display:flex ;
      flex-direction: column;
    }
    #id_orinbosar{
      height: 33px;
    }
    #id_orinbosar option:nth-child(1){
      display: none;
    }
    #id_murajat option:nth-child(1){
      display: none;
    }
  </style>
              <form method="post" style="display: flex; justify-content: space-evenly; align-items: center;">
                {% csrf_token %}
                {{ form | crispy }}
                <div>
                  <button class="btn btn-default btn-flat" style="margin-top: 23px;"
                  type="submit">yuborish
                </button>
                </div>
                
              </form>
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Ism Familiya Sharif</th>
                    <th scope="col">Id Passpord</th>
                    <th scope="col">Yash Manzili</th>
                    <th scope="col">MFY Nomi</th>
                    <th scope="col">Ko`cha Nomi</th>
                    <th scope="col">Tel Raqam</th>
                    <th scope="col">Rasm yoki Vidio</th>
                    <th scope="col">Ariza Tur</th>
                    <th scope="col">matn</th>
                  </tr>
                </thead>
                <tbody>
                {% for ariza in ariza %}
                  
                  <tr>
                    <th scope="row">{{ ariza.id }}</th>
                    <td>{{ ariza.fish }}</td>
                    <td>{{ ariza.idpassport }}</td>
                    <td>{{ ariza.Yashashmanzili }}</td>
                    <td>{{ ariza.mfynomi }}</td>
                    <td>{{ ariza.kochanomi }}</td>
                    <td>{{ ariza.telefonraqami }}</td>
                    <td>{{ ariza.rasmvavidio }}</td>
                    <td>{{ ariza.ariza_mazmuni }}</td>
                    <td><a href='{% url "del" ariza.id %}'>del</a></td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>       
{% endblock content %}

templates/hp_az/hp_az20.html
{% extends "base_hp.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <style>
    #div_id_murajat{
      overflow: hidden;
      display:flex ;
      flex-direction: column;
    }
    #div_id_tashkilot{
      display:flex ;
      flex-direction: column;
    }
    #id_tashkilot{
      height: 33px;
    }
    #id_murajat{
      height: 33px;
    }
    #div_id_bajarildi{
      display: none;
    }
    #div_id_muddat_holati{
      display: none;
    }
    #div_id_orinbosar{
      display:flex ;
      flex-direction: column;
    }
    #id_orinbosar{
      height: 33px;
    }
    #id_orinbosar option:nth-child(1){
      display: none;
    }
    #id_murajat option:nth-child(1){
      display: none;
    }
  </style>
              <form method="post" style="display: flex; justify-content: space-evenly; align-items: center;">
                {% csrf_token %}
                {{ form | crispy }}
                <div>
                  <button class="btn btn-default btn-flat" style="margin-top: 23px;"
                  type="submit">yuborish
                </button>
                </div>
                
              </form>
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Ism Familiya Sharif</th>
                    <th scope="col">Id Passpord</th>
                    <th scope="col">Yash Manzili</th>
                    <th scope="col">MFY Nomi</th>
                    <th scope="col">Ko`cha Nomi</th>
                    <th scope="col">Tel Raqam</th>
                    <th scope="col">Rasm yoki Vidio</th>
                    <th scope="col">Ariza Tur</th>
                    <th scope="col">matn</th>
                  </tr>
                </thead>
                <tbody>
                {% for ariza in ariza %}
                  
                  <tr>
                    <th scope="row">{{ ariza.id }}</th>
                    <td>{{ ariza.fish }}</td>
                    <td>{{ ariza.idpassport }}</td>
                    <td>{{ ariza.Yashashmanzili }}</td>
                    <td>{{ ariza.mfynomi }}</td>
                    <td>{{ ariza.kochanomi }}</td>
                    <td>{{ ariza.telefonraqami }}</td>
                    <td>{{ ariza.rasmvavidio }}</td>
                    <td>{{ ariza.ariza_mazmuni }}</td>
                    <td><a href='{% url "del" ariza.id %}'>del</a></td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>       
{% endblock content %}

templates/hp_az/hp_az21.html
{% extends "base_hp.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <style>
    #div_id_murajat{
      overflow: hidden;
      display:flex ;
      flex-direction: column;
    }
    #div_id_tashkilot{
      display:flex ;
      flex-direction: column;
    }
    #id_tashkilot{
      height: 33px;
    }
    #id_murajat{
      height: 33px;
    }
    #div_id_bajarildi{
      display: none;
    }
    #div_id_muddat_holati{
      display: none;
    }
    #div_id_orinbosar{
      display:flex ;
      flex-direction: column;
    }
    #id_orinbosar{
      height: 33px;
    }
    #id_orinbosar option:nth-child(1){
      display: none;
    }
    #id_murajat option:nth-child(1){
      display: none;
    }
  </style>
              <form method="post" style="display: flex; justify-content: space-evenly; align-items: center;">
                {% csrf_token %}
                {{ form | crispy }}
                <div>
                  <button class="btn btn-default btn-flat" style="margin-top: 23px;"
                  type="submit">yuborish
                </button>
                </div>
                
              </form>
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Ism Familiya Sharif</th>
                    <th scope="col">Id Passpord</th>
                    <th scope="col">Yash Manzili</th>
                    <th scope="col">MFY Nomi</th>
                    <th scope="col">Ko`cha Nomi</th>
                    <th scope="col">Tel Raqam</th>
                    <th scope="col">Rasm yoki Vidio</th>
                    <th scope="col">Ariza Tur</th>
                    <th scope="col">matn</th>
                  </tr>
                </thead>
                <tbody>
                {% for ariza in ariza %}
                  
                  <tr>
                    <th scope="row">{{ ariza.id }}</th>
                    <td>{{ ariza.fish }}</td>
                    <td>{{ ariza.idpassport }}</td>
                    <td>{{ ariza.Yashashmanzili }}</td>
                    <td>{{ ariza.mfynomi }}</td>
                    <td>{{ ariza.kochanomi }}</td>
                    <td>{{ ariza.telefonraqami }}</td>
                    <td>{{ ariza.rasmvavidio }}</td>
                    <td>{{ ariza.ariza_mazmuni }}</td>
                    <td><a href='{% url "del" ariza.id %}'>del</a></td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>       
{% endblock content %}

templates/hp_az/hp_az22.html
{% extends "base_hp.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <style>
    #div_id_murajat{
      overflow: hidden;
      display:flex ;
      flex-direction: column;
    }
    #div_id_tashkilot{
      display:flex ;
      flex-direction: column;
    }
    #id_tashkilot{
      height: 33px;
    }
    #id_murajat{
      height: 33px;
    }
    #div_id_bajarildi{
      display: none;
    }
    #div_id_muddat_holati{
      display: none;
    }
    #div_id_orinbosar{
      display:flex ;
      flex-direction: column;
    }
    #id_orinbosar{
      height: 33px;
    }
    #id_orinbosar option:nth-child(1){
      display: none;
    }
    #id_murajat option:nth-child(1){
      display: none;
    }
  </style>
              <form method="post" style="display: flex; justify-content: space-evenly; align-items: center;">
                {% csrf_token %}
                {{ form | crispy }}
                <div>
                  <button class="btn btn-default btn-flat" style="margin-top: 23px;"
                  type="submit">yuborish
                </button>
                </div>
                
              </form>
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Ism Familiya Sharif</th>
                    <th scope="col">Id Passpord</th>
                    <th scope="col">Yash Manzili</th>
                    <th scope="col">MFY Nomi</th>
                    <th scope="col">Ko`cha Nomi</th>
                    <th scope="col">Tel Raqam</th>
                    <th scope="col">Rasm yoki Vidio</th>
                    <th scope="col">Ariza Tur</th>
                    <th scope="col">matn</th>
                  </tr>
                </thead>
                <tbody>
                {% for ariza in ariza %}
                  
                  <tr>
                    <th scope="row">{{ ariza.id }}</th>
                    <td>{{ ariza.fish }}</td>
                    <td>{{ ariza.idpassport }}</td>
                    <td>{{ ariza.Yashashmanzili }}</td>
                    <td>{{ ariza.mfynomi }}</td>
                    <td>{{ ariza.kochanomi }}</td>
                    <td>{{ ariza.telefonraqami }}</td>
                    <td>{{ ariza.rasmvavidio }}</td>
                    <td>{{ ariza.ariza_mazmuni }}</td>
                    <td><a href='{% url "del" ariza.id %}'>del</a></td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>       
{% endblock content %}

templates/hp_az/hp_az25.html
{% extends "base_hp.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <style>
    #div_id_murajat{
      overflow: hidden;
      display:flex ;
      flex-direction: column;
    }
    #div_id_tashkilot{
      display:flex ;
      flex-direction: column;
    }
    #id_tashkilot{
      height: 33px;
    }
    #id_murajat{
      height: 33px;
    }
    #div_id_bajarildi{
      display: none;
    }
    #div_id_muddat_holati{
      display: none;
    }
    #div_id_orinbosar{
      display:flex ;
      flex-direction: column;
    }
    #id_orinbosar{
      height: 33px;
    }
    #id_orinbosar option:nth-child(1){
      display: none;
    }
    #id_murajat option:nth-child(1){
      display: none;
    }
  </style>
              <form method="post" style="display: flex; justify-content: space-evenly; align-items: center;">
                {% csrf_token %}
                {{ form | crispy }}
                <div>
                  <button class="btn btn-default btn-flat" style="margin-top: 23px;"
                  type="submit">yuborish
                </button>
                </div>
                
              </form>
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Ism Familiya Sharif</th>
                    <th scope="col">Id Passpord</th>
                    <th scope="col">Yash Manzili</th>
                    <th scope="col">MFY Nomi</th>
                    <th scope="col">Ko`cha Nomi</th>
                    <th scope="col">Tel Raqam</th>
                    <th scope="col">Rasm yoki Vidio</th>
                    <th scope="col">Ariza Tur</th>
                    <th scope="col">matn</th>
                  </tr>
                </thead>
                <tbody>
                {% for ariza in ariza %}
                  
                  <tr>
                    <th scope="row">{{ ariza.id }}</th>
                    <td>{{ ariza.fish }}</td>
                    <td>{{ ariza.idpassport }}</td>
                    <td>{{ ariza.Yashashmanzili }}</td>
                    <td>{{ ariza.mfynomi }}</td>
                    <td>{{ ariza.kochanomi }}</td>
                    <td>{{ ariza.telefonraqami }}</td>
                    <td>{{ ariza.rasmvavidio }}</td>
                    <td>{{ ariza.ariza_mazmuni }}</td>
                    <td><a href='{% url "del" ariza.id %}'>del</a></td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>       
{% endblock content %}